name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Initialize Project
        run: |
          # 放弃复杂参数，直接用最基础的指令初始化
          flutter create .
          flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release \
          --dart-define=API_KEY=${{ secrets.API_KEY }} \
          --dart-define=API_SECRET=${{ secrets.API_SECRET }} \
          --dart-define=PASSPHRASE=${{ secrets.PASSPHRASE }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
