name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: |
          flutter build apk --release \
          --dart-define=API_KEY=${{ secrets.API_KEY }} \
          --dart-define=API_SECRET=${{ secrets.API_SECRET }} \
          --dart-define=PASSPHRASE=${{ secrets.PASSPHRASE }}
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
